# Generated by Django 5.2 on 2025-04-06 08:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "bookId",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("genre", models.CharField(max_length=100)),
                ("publishedYear", models.IntegerField()),
                ("totalCopies", models.PositiveIntegerField()),
                ("availableCopies", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "memberId",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("membershipDate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BorrowRecord",
            fields=[
                (
                    "borrowId",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("borrowDate", models.DateTimeField(auto_now_add=True)),
                ("returnDate", models.DateTimeField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.book"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.member"
                    ),
                ),
            ],
        ),
    ]
